# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: "99803452285"
  secret_key: c31914ff6c342f15631fcc33bfc53c70
  canvas_page_name:
  callback_url: http://localhost:3001/
  pretty_errors: true
  set_asset_host_to_callback_url: false

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:

production:
  api_key: 198d260cbfee9f9c99e1d62b4d06aae2
  secret_key: 22326678cdbf8a0a0dc7c1a3d55ba412
  canvas_page_name:
  callback_url: http://localhost:3035/
  pretty_errors: true
  set_asset_host_to_callback_url: false
